global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # --- fb-collector (now HTTP) ---
  - job_name: "fb-collector"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["fb-collector:3001"]
    labels:
      service: "fb-collector"
      protocol: "http"

  # --- ttk-collector (now HTTP) ---
  - job_name: "ttk-collector"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["ttk-collector:3002"]
    labels:
      service: "ttk-collector"
      protocol: "http"

  # --- gateway (unchanged HTTP) ---
  - job_name: "gateway"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["gateway:3000"]
    labels:
      service: "gateway"
      protocol: "http"

  - job_name: "reporter"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["reporter:3003"] # Dedicated metrics port
    labels:
      service: "reporter"
      protocol: "http"
